### PR TITLE
API documentation and a small version nudge

### PR DESCRIPTION
**Pull request by geirawsm**
- Added API documentation to the README
- Added `update_local_repo` to __init__-import for API
- Changed version from 0.0.5 to 0.0.5.1

### CODE REVIEW

**Comment by devxpy** [comment]
Thanks!

Could you please add type annotations as well, to the API docs?

**Comment by geirawsm** [comment]
I'm an amateur programmer so earlier today I had no idea what type annotations was. Hopefully this revision will do ;)

**Comment by devxpy** [comment]
If you're interested in learning how to _properly_ write docs, I would really recommend you look into [readthedocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) and [Sphinx](http://www.sphinx-doc.org/en/master/). [Here's](https://www.youtube.com/watch?v=0ROZRNZkPS8) a video.

Thanks again for the PR. I'll push to pypi and do a shiv bulild when I get some time.

**Comment by geirawsm** [comment]
Thanks, I'll look into it.
No worries, glad I could help (and learn) =)

**Pull request merged**
